apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-app-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GHARBIyasmine/argocd-demo.git
    targetRevision: HEAD
    path: basic/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: basic-app-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

 
 
